In [3]:
# MIDTERM - Predict Class
import numpy as np # linear algebra
import matplotlib.pyplot as plt # For plotting
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [4]:
dataset = pd.read_csv(r'C:\Users\saedw\OneDrive\Desktop\CECS 456 Machine Learning\Data\Data_Midterm.csv')
# print snapshot of dataset
dataset

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0               1000025                5                        1   
1               1002945                5                        4   
2               1015425                3                        1   
3               1016277                6                        8   
4               1017023                4                        1   
..                  ...              ...                      ...   
678              776715                3                        1   
679              841769                2                        1   
680              888820                5                       10   
681              897471                4                        8   
682              897471                4                        8   

     Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                           1                  1                            2   
1                           4                  5                            7   
2                           1                  1                            2   
3                           8                  1                            3   
4                           1                  3                            2   
..                        ...                ...                          ...   
678                         1                  1                            3   
679                         1                  1                            2   
680                        10                  3                            7   
681                         6                  4                            3   
682                         8                  5                            4   

     Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0              1                3                1        1      2  
1             10                3                2        1      2  
2              2                3                1        1      2  
3              4                3                7        1      2  
4              1                3                1        1      2  
..           ...              ...              ...      ...    ...  
678            2                1                1        1      2  
679            1                1                1        1      2  
680            3                8               10        2      4  
681            4               10                6        1      4  
682            5               10                4        1      4  

[683 rows x 11 columns]

In [5]:
# x needs to be a matrix for model - contain all predictor variables
x = dataset.iloc[:, [1, 2, 3, 4, 5, 6, 7, 8, 9]].values
y = dataset.iloc[:, 10].values

In [6]:
# Splitting the dataset into the Training set and Test set
# TEST AND TRAINING MODELS USED FOR FOLLOWING MODELS
    # Kernels, Decision Trees, Random Forest, KNN, Logistic Regression, mabye XG Boosting
# Train = .80 Test = .20
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 0)

# Feature Scaling - scale the data after training 
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [7]:
# Gaussion Kernal Model - predicting Class (2 or 4)
# Fitting classifier to the Training set
from sklearn.ensemble import RandomForestClassifier
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
# define our kernel
kernel = 1.0 * RBF(1.0)
# selecting gaussian process classifier and fit model on training data
classifier_kernel = GaussianProcessClassifier(kernel=kernel, random_state=0).fit(X_train, y_train)

# Predicting the Test set results
# y_pred holds all of the predicted values for the data set
y_pred_kernel = classifier_kernel.predict(X_test)

# Confusion Matrix
print ("Confusion Matrix - Gaussian Kernal\n {}".format(confusion_matrix(y_test, y_pred_kernel)))
# Accuracy Score
print ("Accuracy score on Test data - Gaussian Kernal\n {}".format(accuracy_score(y_test, y_pred_kernel)))

Confusion Matrix - Gaussian Kernal
 [[84  3]
 [ 3 47]]
Accuracy score on Test data - Gaussian Kernal
 0.9562043795620438


In [8]:
# RANDOM FOREST MODEL
# Fitting classifier to the Training set
from sklearn.ensemble import RandomForestClassifier
# selecting n_estimators - default is 10
classifierRandomForest = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
# fit the model on training data sets X_train and y_train
classifierRandomForest.fit(X_train, y_train)

# Predicting the Test set results
# y_pred holds all of the predicted values for the data set
y_predRandomForest = classifierRandomForest.predict(X_test)


# Confusion Matrix
print ("Confusion Matrix - Random Forest Model\n {}".format(confusion_matrix(y_test, y_predRandomForest)))
# Accuracy Score
print ("Accuracy score on Test data - Random Forest Model\n {}".format(accuracy_score(y_test, y_predRandomForest)))

Confusion Matrix - Random Forest Model
 [[83  4]
 [ 3 47]]
Accuracy score on Test data - Random Forest Model
 0.948905109489051


In [9]:
# KNN MODEL
# Fitting classifier to the Training set
from sklearn.neighbors import KNeighborsClassifier
# k=5 neighbors
classifier_knn = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)
classifier_knn.fit(X_train, y_train)

# Predicting the Test set results
y_pred_knn = classifier_knn.predict(X_test)


# Confusion Matrix
print ("Confusion Matrix - KNN\n {}".format(confusion_matrix(y_test, y_pred_knn)))
# Accuracy Score
print ("Accuracy score on Test data  - KNN\n {}".format(accuracy_score(y_test, y_pred_knn)))

Confusion Matrix - KNN
 [[83  4]
 [ 2 48]]
Accuracy score on Test data  - KNN
 0.9562043795620438


In [10]:
# LOGISTIC REGRESSION MODEL
# Fit classifier to training set
from sklearn.linear_model import LogisticRegression
classifier_logistic = LogisticRegression()
classifier_logistic.fit(X_train, y_train)

# Predict Test results
y_pred_logistic = classifier_logistic.predict(X_test)

# Confusion Matrix
print("Confusion Matrix - Logistic Classification\n {}".format(confusion_matrix(y_test, y_pred_logistic)))
# Accuracy Score
print("Accuracy Score - Logistic Classification\n {}".format(accuracy_score(y_test, y_pred_logistic)))


Confusion Matrix - Logistic Classification
 [[84  3]
 [ 3 47]]
Accuracy Score - Logistic Classification
 0.9562043795620438


In [42]:
# Support Vector - K-fold cross validation and Grid Search

# Step 1 K-fold cross validation
from sklearn.model_selection import KFold 
from sklearn.svm import SVC



# x needs to be a matrix for model - contain all predictor variables
X = dataset.iloc[:, [1, 2, 3, 4, 5, 6, 7, 8, 9]].values
y = dataset.iloc[:, 10].values

k = 10
kf = KFold(n_splits=k, random_state=None)
model = SVC(kernel='linear', random_state=0)
 
acc_score = []
cm_holder = []
 
for train_index , test_index in kf.split(X):
    X_train , X_test = X[train_index,:],X[test_index,:]
    y_train , y_test = y[train_index] , y[test_index]
     
    model.fit(X_train,y_train)
    pred_values = model.predict(X_test)
     
    acc = accuracy_score(pred_values , y_test)
    acc_score.append(acc)
    
    cm = confusion_matrix(pred_values, y_test)
    cm_holder.append(cm)
     
avg_acc_score = sum(acc_score)/k
avg_confusion_matrix = sum(cm_holder)/k
 
print("Confusion Matrix - Support Vector (k-fold cross validation)\n".format(avg_confusion_matrix))
print('Avg accuracy : {}'.format(avg_acc_score))


Confusion Matrix - Support Vector (k-fold cross validation)

Avg accuracy : 0.9663469735720376


In [41]:
from xgboost import XGBClassifier

x = dataset.iloc[:, [1, 2, 3, 4, 5, 6, 7, 8, 9]].values
y = dataset.iloc[:, 10].values

y = (y-2)/2

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 0)


# fit model no training data
classifier_xgb = XGBClassifier()
classifier_xgb.fit(X_train, y_train)


# make predictions for test data
y_predxgb = classifier_xgb.predict(X_test)

# Confusion Matrix
print("Confusion Matrix - XG Boost Classification\n {}".format(confusion_matrix(y_test, y_predxgb)))
# Accuracy Score
print("Accuracy Score - XG Boost Classification\n {}".format(accuracy_score(y_test, y_predxgb)))


Confusion Matrix - Logistic Classification
 [[84  3]
 [ 1 49]]
Accuracy Score - Logistic Classification
 0.9708029197080292
